# See README.md on how to use this config
version: "3.9"
services:
  minio:
    image: minio/minio:RELEASE.2021-04-06T23-11-00Z
    volumes:
      - ./storage/minio:/data
    ports:
      - "9001:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
